
model_name : Res2Net

result_path : './result/'
train : true
infer : false




training :
  
  batch_size : 128

#   batch_size : 
  epoch : 100
  num_class : 4
  learing_rate : 0.0001
  optimizer: Adam  
  callbacks:
    early_stopping:
      patience: 5
    model_checkpoint :
      filepath : './result/'
      monitor : periodic
data :

  data_dir : './data/'
  shuffle : True
  val_holdout_frac : 0.2  
    
    
    