
model_name : Res2Net

result_path : './result/'
train : true
infer : false




training :
  
  batch_size : 64
#   batch_size : 1
  epoch : 1
  num_class : 189
  learing_rate : 0.0001
  optimizer: Adam  
  callbacks:
    early_stopping:
      patience: 50
    model_checkpoint :
      filepath : './result/'
      monitor : periodic
data :

  data_dir : './data/'
  shuffle : True
  val_holdout_frac : 0.2  
    
    
    